### ISSUE TITLE
Long messages to Slack are truncated

### ISSUE THREAD

**Issue by roadtrippers-rops** [StackStorm/hubot-stackstorm#108]
If `chatops.post_message` is given a sufficiently long message, it is truncated, and its length does not seem to be adjustable. I tested via the [Slack documentation-based tester](https://api.slack.com/docs/formatting/builder), and the full message is retained. It appears to be truncated at some point by hubot-stackstorm.

Setting `ST2_MAX_MESSAGE_LENGTH` had no effect. I believe that is the case because of [this comment](https://github.com/StackStorm/hubot-stackstorm/blob/f2dfdd82f68a27e73f35fff5d542a202b0d0d08b/lib/format_data.js#L38).

**Comment by emedvedev** [comment]
Thanks, I'll look into it. Can you elaborate on what's "a sufficiently long message"? How many chars are we talking about here?

**Comment by jmound** [comment]
```
$ wc -m  output.txt 
   12012 output.txt
```
It's a long, somewhat complex ansible run.

**Comment by emedvedev** [comment]
Thanks! I'll try to reproduce in a couple days and will get back to you. We don't truncate Slack output, so there's probably an implicit limit somewhere.

**Comment by jmound** [comment]
I tried to verify it was stackstorm doing the limiting by sending it via `curl` to the slack API, but the `@filename` syntax was proving to be too finicky.

**Comment by emedvedev** [comment]
I looked into it, and it's a truncation on the Slack side. It's exactly 8000 bytes, and it seems that's the most you can send via an attachment. Slack doesn't mention the limit, but I found a reference to it in someone else's code as well: https://github.com/papertrail/papertrail-services/blob/master/services/slack.rb#L36 Weirdly enough, Slack tester also truncates the attachment, but somewhat further.

Splitting long output into multiple attachments is fairly easy to implement though, so if you want to try your hand at it, that's where you need to do it: https://github.com/StackStorm/hubot-stackstorm/blob/master/lib/post_data.js#L64
Check the length of `split_message.text` and send it over multiple attachments if it's over 8000 bytes long, that should do it.
