### ISSUE TITLE
ChatOps via private messages fails with 500

### ISSUE THREAD

**Issue by armab** [StackStorm/hubot-stackstorm#11]
> reported by `@mick27` from IRC

When playing with chatops commands in the room (Slack room in our case) - it works ok.

When sending private message to bot, it returns 500:
![pm](http://i.imgur.com/B1A9Ghe.png)
(reproduced in Slack)

PM most probably is not the best way for ChatOps, but we should avoid user confusion here.

At least should be some more user-friendly message asking to use chat room (otherwise fix chatops via PM).

**Comment by emedvedev** [comment]
Closing, not relevant anymore (probably for a long time).
