### ISSUE TITLE
Expose Execution URL as a variable

### ISSUE THREAD

**Issue by armab** [StackStorm/hubot-stackstorm#120]
In some previous ChatOps version the URL with results was [always included](http://i.imgur.com/IT2EDcn.png) in message:

> Execution Details available at: http://... 

In the new and more flexible ChatOps version with formatting and everything it's missing now. 

Some tasks could be really long-running and having full execution URL would be nice, so user can include it with own formatted `result` message (Jinja2 stuff in Action Alias). Ideally to make it available as ready-to use variable.

**Comment by emedvedev** [comment]
That's reasonable. Just wondering: the link in the `ack` message isn't enough for your case, or did you find it was better to disable the link / entire ack?

**Comment by armab** [comment]
Yeah, the case is a long-running task, when `ack` with link appears in chat immediately, but the actual `result` can appear in chat after several minutes of execution.

So link in `ack` is not enough.

**Comment by Kami** [comment]
Yeah, if possible I think having execution URL in the context which is available to the message would be nice.

**Comment by armab** [comment]
So this is implemented and available via Jinja variable `{{ execution.web_url }}` in ChatOps alias

See: 
https://github.com/StackStorm/st2/blob/ed6fdb4043647b766551c25f365782a58abce019/contrib/chatops/actions/templates/default.j2#L17-L19
