### ISSUE TITLE
hubot-slack 4.x API has changed. SlackPostDataHandler needs to use new APIs.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/hubot-stackstorm#137]
https://github.com/slackapi/hubot-slack/pull/355/files

Related: https://github.com/StackStorm/st2chatops/pull/78
https://github.com/StackStorm/st2/issues/2896

**Comment by armab** [comment]
Fixed since st2chatops v2.4.0 https://github.com/StackStorm/st2chatops/pull/78
