### ISSUE TITLE
Update st2client.js to support customizing st2stream url

### ISSUE THREAD

**Issue by shusugmt** [StackStorm/hubot-stackstorm#143]
Currently, URL for st2stream is fixed to `$ST2_API/stream`

This is not ideal if running 1ppc mode in st2-docker because without that, st2chatops need to rely on st2web container running nginx which proxies `/api/stream` to st2stream backend.

**Comment by armab** [comment]
:+1: for a configurable env var, similar to existing [`ST2_AUTH_URL`](https://github.com/StackStorm/st2chatops/blob/9de21f73beba4d0ff1e106958a80f5d33a2053ef/st2chatops.env#L26).

**Comment by shusugmt** [comment]
@armab I just opened PR for this. Can you please check it?

**Comment by shusugmt** [comment]
#144 solved this.
