### ISSUE TITLE
StackStorm with Hubot adapter for botframework

### ISSUE THREAD

**Issue by thefossgeek** [StackStorm/hubot-stackstorm#150]
Microsoft has posted a Bot Framework Hubot adapter[1]. Have anyone manage to actually get hubot connected with MS teams? 

I am looking forward StackStorm integration with MS team using Bot Framework Hubot adapter. 

[1]. Hubot adapter for botframework: https://github.com/Microsoft/BotFramework-Hubot

**Comment by thefossgeek** [comment]
Here is discussion about Hubot for Microsoft Teams: https://github.com/hubotio/hubot/issues/1260.

**Comment by blag** [comment]
Initial support for ChatOps response/reply is incoming in StackStorm 3.0. Adding end-to-end tests with MS Teams and supporting `chatops.post_message` should be complete in StackStorm 3.1.

**Comment by armab** [comment]
Just a confirmation update that Microsoft Teams was indeed added in StackStorm v3.0:
https://stackstorm.com/2019/04/29/its-here-stackstorm-3-0/

Feel free to use it and share your feedback or issues.
