### ISSUE TITLE
Add tests for #182/#183

### ISSUE THREAD

**Issue by blag** [StackStorm/hubot-stackstorm#184]
#182 was a regression, but we should add a test for that so we don't regress again in the future. Opening this issue to track the status of that.

**Comment by armab** [comment]
Yeah, having those ^^ changes minimal/granular as possible still hit the regressions. I'm afraid to think what would happen with multiple changes coming in https://github.com/StackStorm/hubot-stackstorm/pull/168.

Minimally, something along the lines would be useful to test: 
- `Nock` the failing HTTP response from ST2 API. Ensure that function doesn't throw and that hubot doesn't exit.
- Additionally need to ensure that the warning message is sent back to chat as well:
![](https://i.imgur.com/w4y9jfL.png)

**Comment by blag** [comment]
@armab Yep, I think we all made the right call (thanks to you).

If we need to check the output we should simply make it an end-to-end test in st2tests. I’ll do that next week; should be pretty straightforward.

**Comment by armab** [comment]
Thanks, I'll take care of the first part then: Nock/HTTP unit test in this repo to ensure hubot doesn't exit.
