### ISSUE TITLE
hubot-stackstorm not responding with result in Mattermost

### ISSUE THREAD

**Issue by ChickenNotHD** [StackStorm/hubot-stackstorm#188]
Original forum thread: https://forum.stackstorm.com/t/st2chatops-with-mattermost-not-replying/711

Created at the request of @armab 

Good morning,

Currently, hubot-stackstorm does not respond with the output/result of a stackstorm command on Mattermost.

Here is what happens when I send `!pack get docker`

1. Bot successfully reads my command.
2. Stackstorm successfully runs the command.
3. The output is sent to the event stream.
4. Bot receives the message (this can be seen in the logs as `Chatops message received` followed by the JSON of the correct output)
5. Bot does nothing else.

I have tested this with Mattermost 5.4.0, 5.9.0 and 5.12.3 on two different networks (one connected to the Internet and one not). I have tried using the Slack adapter with the same settings instead and it works as expected. I have tried using errbot with a Mattermost adapter and a Stackstorm adapter and it also works.

I recommend reading the forum thread at the top of this issue if you have any questions, as it has been most likely answered in there.

**Comment by armab** [comment]
Thanks for reporting this!

I think @blag was trying to reproduce Mattermost issue in his environment.
I'll let him share his findings and plans.

**Comment by armab** [comment]
Fixed in https://github.com/StackStorm/hubot-stackstorm/pull/192
