### ISSUE TITLE
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

### ISSUE THREAD

**Issue by pradiptadas115** [StackStorm/hubot-stackstorm#196]
When I try to run ` npm install hubot-stackstorm` 
I am getting this issue :

`root@56914a14ea3b:~/myhubot# npm install hubot-stackstorm`
`npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`
`npm ERR! code ENOVERSIONS`
`npm ERR! No valid versions available for st2client`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /root/.npm/_logs/2019-08-27T09_31_24_173Z-debug.log`    
`

**Comment by armab** [comment]
Is there anything more specific in ` /root/.npm/_logs/2019-08-27T09_31_24_173Z-debug.log` ?

**Comment by pradiptadas115** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'hubot-stackstorm' ]
2 info using npm@6.4.1
3 info using node@v10.14.0
4 verbose npm-session 19ea4cb89db12a5a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/hubot-stackstorm 38ms (from cache)
8 silly pacote tag manifest for hubot-stackstorm@latest fetched in 58ms
9 timing stage:loadCurrentTree Completed in 765ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 6ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 240ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule hubot-stackstorm@0.10.0 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/st2client 59ms (from cache)
18 silly fetchPackageMetaData error for st2client@^1.1.3 No valid versions available for st2client
19 http fetch GET 304 https://registry.npmjs.org/cli-table 325ms (from cache)
20 silly pacote range manifest for cli-table@<=1.0.0 fetched in 326ms
21 silly resolveWithNewModule cli-table@0.3.1 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/coffee-script 344ms (from cache)
23 silly pacote version manifest for coffee-script@1.12.7 fetched in 346ms
24 warn deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
25 silly resolveWithNewModule coffee-script@1.12.7 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/rsvp 408ms (from cache)
27 silly pacote range manifest for rsvp@^4.8.4 fetched in 418ms
28 silly resolveWithNewModule rsvp@4.8.5 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/truncate 450ms (from cache)
30 silly pacote range manifest for truncate@^2.0.1 fetched in 453ms
31 silly resolveWithNewModule truncate@2.1.0 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/coffee-register 1924ms (from cache)
33 silly pacote version manifest for coffee-register@1.0.0 fetched in 1925ms
34 silly resolveWithNewModule coffee-register@1.0.0 checking installable status
35 timing stage:rollbackFailedOptional Completed in 0ms
36 timing stage:runTopLevelLifecycles Completed in 2951ms
37 silly saveTree myhubot@0.0.0
37 silly saveTree ├── hubot-diagnostics@1.0.0
37 silly saveTree ├── hubot-google-images@0.2.7
37 silly saveTree ├── hubot-google-translate@0.2.1
37 silly saveTree ├── hubot-help@1.0.1
37 silly saveTree ├── hubot-heroku-keepalive@1.0.3
37 silly saveTree ├── hubot-maps@0.0.3
37 silly saveTree ├── hubot-pugme@0.1.1
37 silly saveTree ├─┬ hubot-redis-brain@1.0.0
37 silly saveTree │ └─┬ redis@2.8.0
37 silly saveTree │   ├── double-ended-queue@2.1.0-0
37 silly saveTree │   ├── redis-commands@1.5.0
37 silly saveTree │   └── redis-parser@2.6.0
37 silly saveTree ├── hubot-rules@1.0.0
37 silly saveTree ├─┬ hubot-scripts@2.17.2
37 silly saveTree │ └── redis@0.8.4
37 silly saveTree ├── hubot-shipit@0.2.1
37 silly saveTree ├─┬ hubot-slack@4.7.1
37 silly saveTree │ ├─┬ @slack/client@3.16.1-sec.2
37 silly saveTree │ │ ├── async@1.5.2
37 silly saveTree │ │ ├── bluebird@3.5.5
37 silly saveTree │ │ ├── eventemitter3@1.2.0
37 silly saveTree │ │ ├─┬ https-proxy-agent@2.2.2
37 silly saveTree │ │ │ ├─┬ agent-base@4.3.0
37 silly saveTree │ │ │ │ └─┬ es6-promisify@5.0.0
37 silly saveTree │ │ │ │   └── es6-promise@4.2.8
37 silly saveTree │ │ │ └─┬ debug@3.2.6
37 silly saveTree │ │ │   └── ms@2.1.2
37 silly saveTree │ │ ├── inherits@2.0.4
37 silly saveTree │ │ ├── lodash@4.17.15
37 silly saveTree │ │ ├── pkginfo@0.4.1
37 silly saveTree │ │ ├─┬ request@2.88.0
37 silly saveTree │ │ │ ├── aws-sign2@0.7.0
37 silly saveTree │ │ │ ├── aws4@1.8.0
37 silly saveTree │ │ │ ├── caseless@0.12.0
37 silly saveTree │ │ │ ├─┬ combined-stream@1.0.8
37 silly saveTree │ │ │ │ └── delayed-stream@1.0.0
37 silly saveTree │ │ │ ├── extend@3.0.2
37 silly saveTree │ │ │ ├── forever-agent@0.6.1
37 silly saveTree │ │ │ ├─┬ form-data@2.3.3
37 silly saveTree │ │ │ │ ├── asynckit@0.4.0
37 silly saveTree │ │ │ │ └─┬ mime-types@2.1.24
37 silly saveTree │ │ │ │   └── mime-db@1.40.0
37 silly saveTree │ │ │ ├─┬ har-validator@5.1.3
37 silly saveTree │ │ │ │ ├─┬ ajv@6.10.2
37 silly saveTree │ │ │ │ │ ├── fast-deep-equal@2.0.1
37 silly saveTree │ │ │ │ │ ├── fast-json-stable-stringify@2.0.0
37 silly saveTree │ │ │ │ │ ├── json-schema-traverse@0.4.1
37 silly saveTree │ │ │ │ │ └─┬ uri-js@4.2.2
37 silly saveTree │ │ │ │ │   └── punycode@2.1.1
37 silly saveTree │ │ │ │ └── har-schema@2.0.0
37 silly saveTree │ │ │ ├─┬ http-signature@1.2.0
37 silly saveTree │ │ │ │ ├── assert-plus@1.0.0
37 silly saveTree │ │ │ │ ├─┬ jsprim@1.4.1
37 silly saveTree │ │ │ │ │ ├── extsprintf@1.3.0
37 silly saveTree │ │ │ │ │ ├── json-schema@0.2.3
37 silly saveTree │ │ │ │ │ └─┬ verror@1.10.0
37 silly saveTree │ │ │ │ │   └── core-util-is@1.0.2
37 silly saveTree │ │ │ │ └─┬ sshpk@1.16.1
37 silly saveTree │ │ │ │   ├─┬ asn1@0.2.4
37 silly saveTree │ │ │ │   │ └── safer-buffer@2.1.2
37 silly saveTree │ │ │ │   ├─┬ bcrypt-pbkdf@1.0.2
37 silly saveTree │ │ │ │   │ └── tweetnacl@0.14.5
37 silly saveTree │ │ │ │   ├── dashdash@1.14.1
37 silly saveTree │ │ │ │   ├─┬ ecc-jsbn@0.1.2
37 silly saveTree │ │ │ │   │ └── jsbn@0.1.1
37 silly saveTree │ │ │ │   ├── getpass@0.1.7
37 silly saveTree │ │ │ │   ├── jsbn@0.1.1
37 silly saveTree │ │ │ │   ├── safer-buffer@2.1.2
37 silly saveTree │ │ │ │   └── tweetnacl@0.14.5
37 silly saveTree │ │ │ ├── is-typedarray@1.0.0
37 silly saveTree │ │ │ ├── isstream@0.1.2
37 silly saveTree │ │ │ ├── json-stringify-safe@5.0.1
37 silly saveTree │ │ │ ├── mime-types@2.1.24
37 silly saveTree │ │ │ ├── oauth-sign@0.9.0
37 silly saveTree │ │ │ ├── performance-now@2.1.0
37 silly saveTree │ │ │ ├── qs@6.5.2
37 silly saveTree │ │ │ ├── safe-buffer@5.1.2
37 silly saveTree │ │ │ ├─┬ tough-cookie@2.4.3
37 silly saveTree │ │ │ │ ├── psl@1.3.0
37 silly saveTree │ │ │ │ └── punycode@1.4.1
37 silly saveTree │ │ │ ├── tunnel-agent@0.6.0
37 silly saveTree │ │ │ └── uuid@3.3.3
37 silly saveTree │ │ ├── retry@0.9.0
37 silly saveTree │ │ ├── url-join@0.0.1
37 silly saveTree │ │ ├─┬ winston@2.4.4
37 silly saveTree │ │ │ ├── async@1.0.0
37 silly saveTree │ │ │ ├── colors@1.0.3
37 silly saveTree │ │ │ ├── cycle@1.0.3
37 silly saveTree │ │ │ ├── eyes@0.1.8
37 silly saveTree │ │ │ └── stack-trace@0.0.10
37 silly saveTree │ │ └─┬ ws@1.1.5
37 silly saveTree │ │   ├── options@0.0.6
37 silly saveTree │ │   └── ultron@1.0.2
37 silly saveTree │ ├── bluebird@3.5.5
37 silly saveTree │ └── lodash@4.17.15
37 silly saveTree ├─┬ hubot-stackstorm@0.10.0
37 silly saveTree │ ├── cli-table@0.3.1
37 silly saveTree │ ├── coffee-register@1.0.0
37 silly saveTree │ ├── coffee-script@1.12.7
37 silly saveTree │ ├── rsvp@4.8.5
37 silly saveTree │ └── truncate@2.1.0
37 silly saveTree └─┬ hubot@3.3.2
37 silly saveTree   ├── async@0.9.2
37 silly saveTree   ├─┬ chalk@1.1.3
37 silly saveTree   │ ├── ansi-styles@2.2.1
37 silly saveTree   │ ├── escape-string-regexp@1.0.5
37 silly saveTree   │ ├─┬ has-ansi@2.0.0
37 silly saveTree   │ │ └── ansi-regex@2.1.1
37 silly saveTree   │ ├── strip-ansi@3.0.1
37 silly saveTree   │ └── supports-color@2.0.0
37 silly saveTree   ├── cline@0.8.2
37 silly saveTree   ├── coffeescript@1.6.3
37 silly saveTree   ├─┬ connect-multiparty@2.2.0
37 silly saveTree   │ ├─┬ http-errors@1.7.3
37 silly saveTree   │ │ ├── depd@1.1.2
37 silly saveTree   │ │ ├── setprototypeof@1.1.1
37 silly saveTree   │ │ ├── statuses@1.5.0
37 silly saveTree   │ │ └── toidentifier@1.0.0
37 silly saveTree   │ ├─┬ multiparty@4.2.1
37 silly saveTree   │ │ ├─┬ fd-slicer@1.1.0
37 silly saveTree   │ │ │ └── pend@1.2.0
37 silly saveTree   │ │ └─┬ uid-safe@2.1.5
37 silly saveTree   │ │   └── random-bytes@1.0.0
37 silly saveTree   │ ├─┬ on-finished@2.3.0
37 silly saveTree   │ │ └── ee-first@1.1.1
37 silly saveTree   │ └─┬ type-is@1.6.18
37 silly saveTree   │   └── media-typer@0.3.0
37 silly saveTree   ├─┬ express@4.17.1
37 silly saveTree   │ ├─┬ accepts@1.3.7
37 silly saveTree   │ │ └── negotiator@0.6.2
37 silly saveTree   │ ├── array-flatten@1.1.1
37 silly saveTree   │ ├─┬ body-parser@1.19.0
37 silly saveTree   │ │ ├── bytes@3.1.0
37 silly saveTree   │ │ ├── content-type@1.0.4
37 silly saveTree   │ │ ├─┬ debug@2.6.9
37 silly saveTree   │ │ │ └── ms@2.0.0
37 silly saveTree   │ │ ├─┬ http-errors@1.7.2
37 silly saveTree   │ │ │ └── inherits@2.0.3
37 silly saveTree   │ │ ├── iconv-lite@0.4.24
37 silly saveTree   │ │ ├── qs@6.7.0
37 silly saveTree   │ │ └─┬ raw-body@2.4.0
37 silly saveTree   │ │   ├─┬ http-errors@1.7.2
37 silly saveTree   │ │   │ └── inherits@2.0.3
37 silly saveTree   │ │   └── unpipe@1.0.0
37 silly saveTree   │ ├── content-disposition@0.5.3
37 silly saveTree   │ ├── content-type@1.0.4
37 silly saveTree   │ ├── cookie-signature@1.0.6
37 silly saveTree   │ ├── cookie@0.4.0
37 silly saveTree   │ ├── debug@2.6.9
37 silly saveTree   │ ├── encodeurl@1.0.2
37 silly saveTree   │ ├── escape-html@1.0.3
37 silly saveTree   │ ├── etag@1.8.1
37 silly saveTree   │ ├─┬ finalhandler@1.1.2
37 silly saveTree   │ │ └── parseurl@1.3.3
37 silly saveTree   │ ├── fresh@0.5.2
37 silly saveTree   │ ├── merge-descriptors@1.0.1
37 silly saveTree   │ ├── methods@1.1.2
37 silly saveTree   │ ├── parseurl@1.3.3
37 silly saveTree   │ ├── path-to-regexp@0.1.7
37 silly saveTree   │ ├─┬ proxy-addr@2.0.5
37 silly saveTree   │ │ ├── forwarded@0.1.2
37 silly saveTree   │ │ └── ipaddr.js@1.9.0
37 silly saveTree   │ ├── qs@6.7.0
37 silly saveTree   │ ├── range-parser@1.2.1
37 silly saveTree   │ ├─┬ send@0.17.1
37 silly saveTree   │ │ ├── destroy@1.0.4
37 silly saveTree   │ │ ├── mime@1.6.0
37 silly saveTree   │ │ └── ms@2.1.1
37 silly saveTree   │ ├── serve-static@1.14.1
37 silly saveTree   │ ├── utils-merge@1.0.1
37 silly saveTree   │ └── vary@1.1.2
37 silly saveTree   ├── log@1.4.0
37 silly saveTree   ├── optparse@1.0.4
37 silly saveTree   └── scoped-http-client@0.11.0
38 verbose type range
39 verbose stack st2client: No valid versions available for st2client
39 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:20:11)
39 verbose stack     at fetchPackument.then.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
39 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
39 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
39 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
39 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
39 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
39 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
39 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
39 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
39 verbose stack     at runCallback (timers.js:705:18)
39 verbose stack     at tryOnImmediate (timers.js:676:5)
39 verbose stack     at processImmediate (timers.js:658:5)
40 verbose cwd /root/myhubot
41 verbose Linux 4.4.0-87-generic
42 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "hubot-stackstorm"
43 verbose node v10.14.0
44 verbose npm  v6.4.1
45 error code ENOVERSIONS
46 error No valid versions available for st2client
47 verbose exit [ 1, true ]

**Comment by armab** [comment]
Thanks for the report!

Looks like https://www.npmjs.com/package/st2client is missing for some reason.

**Comment by pradiptadas115** [comment]
@armab what should I do ?

**Comment by armab** [comment]
https://www.npmjs.com/package/st2client is back and recovered, thanks to @blag

@pradiptadas115 Installation should now work properly. Thanks for your report!
