### ISSUE TITLE
chatops with hubot slack and stackstorm

### ISSUE THREAD

**Issue by kanusoni** [StackStorm/hubot-stackstorm#205]
Hi,
 
i have integrated slack hubot with stackstorm, hubot is online, it's answering but only help command is working. can you please let me know how we can create our own alias or actions in stackstorm for making bot more intelligent.

**Comment by blag** [comment]
ChatOps documentation is located here: https://docs.stackstorm.com/chatops/aliases.html

If you need additional help, the StackStorm Slack community is very active (the #community and #chatops channels will be the most helpful for you):
https://stackstorm-community.slack.com

Closing this issue, but if you run into any bugs in the hubot-stackstorm code, feel free to open a new issue in this repository. There is also the StackStorm/st2chatops project if you run into any issues with st2chatops packaging, and there are individual Hubot plugins for the various chat providers. The Slack plugin for Hubot is located here: https://github.com/slackapi/hubot-slack
