### ISSUE TITLE
Oops; flutter has exited unexpectedly: "Bad state: The client closed with pending request "streamListen".".

### ISSUE THREAD

**Issue by smailbouramdane** [StackStorm/hubot-stackstorm#210]
![Capture d’écran 2020-10-01 à 00 19 45](https://user-images.githubusercontent.com/72172228/94749545-f7e87700-037b-11eb-8e7b-31e47f6682a9.png)
![Capture d’écran 2020-10-01 à 00 20 40](https://user-images.githubusercontent.com/72172228/94749547-f919a400-037b-11eb-8525-26445a5db680.png)

**Comment by smailbouramdane** [comment]
[flutter_10.log](https://github.com/StackStorm/hubot-stackstorm/files/5308688/flutter_10.log)

**Comment by smailbouramdane** [comment]
![Capture d’écran 2020-10-01 à 00 23 38](https://user-images.githubusercontent.com/72172228/94749713-60cfef00-037c-11eb-8fd5-f5fcdf8208ca.png)

**Comment by nmaludy** [comment]
I don't think this is the right repo.
