### ISSUE TITLE
Bump hubot peerdependency from version 3.x to 11

### ISSUE THREAD

**Issue by inakiuy** [StackStorm/hubot-stackstorm#235]
I am reaching out to inquire about the current state of the hubot-stackstorm plugin, specifically regarding its compatibility with newer versions of Hubot.

Hubot has evolved and is currently at version 11. However, the hubot-stackstorm plugin seems to be using an older peer dependency of Hubot (version 3.x). I am curious to know if there are any ongoing efforts or plans to update this dependency to be compatible with the latest version of Hubot.

I understand that maintaining open-source projects can be challenging, and I appreciate all the hard work that goes into it. I am also aware that sometimes projects may not be as active as they once were. Therefore, I would like to gauge the current activity level within this community and see if there is interest in such an update.

If there are no current plans for this update, I am considering undertaking this endeavor myself. However, before proceeding, I am eager to learn if there are other community members who might be interested in supporting this update, or if there are any specific guidelines or considerations I should take into account.

Thank you for your time and all the contributions to this project. I look forward to your response and hope to potentially collaborate with this project.

**Comment by nzlosh** [comment]
The intention is to move off hubot and switch to Opsdroid https://github.com/StackStorm/community/issues/8 https://github.com/StackStorm/community/issues/56

The reality is that work isn't ready and hubot support hasn't been maintained.

Ideally, someone would pickup the Opsdroid work rather than reanimate hubot.  If you feel compelled to update hubot, then your contributions would be welcome but know that at some point in the future, hubot would be dropped.

As always, err-stackstorm https://err-stackstorm.readthedocs.io/en/latest/ is available now for anyone who would like to make use of it.

**Comment by nzlosh** [comment]
FYI: @amanda11 and @philipphomberger have recently created PRs to updating hubot, there may be an opportunity here to collaborate / share the workload if that's something that would be of interest.

**Comment by philipphomberger** [comment]
@nzlosh  Good to Know. I just see the tutorial @amanda11  posted on slack. And just try to do some process on that chatops node update stuff. :)

**Comment by inakiuy** [comment]
> The intention is to move off hubot and switch to Opsdroid [StackStorm/community#8]

Great to know that. Had no idea that Opsdroid was the next step for ST2 chatops.

> Ideally, someone would pickup the Opsdroid work rather than reanimate hubot. If you feel compelled to update hubot, then your contributions would be welcome but know that at some point in the future, hubot would be dropped.

Makes sense....

> As always, err-stackstorm https://err-stackstorm.readthedocs.io/en/latest/ is available now for anyone who would like to make use of it.

We use DISCORD at our company. To make errbot's discord adapter to work I had to patch the code. I submited a PR that was merged to the "fix person" branch but it's still not merged into main. https://github.com/errbotio/err-backend-discord/tree/fix_person.

My team and I will be evaluating our next steps and I'll keep you posted.

THX!!!

**Comment by nzlosh** [comment]
@inakiuy Thanks for pointing that out, I've merge the PR to main.
