### ISSUE TITLE
Weird output in chatops

### ISSUE THREAD

**Issue by emptywee** [StackStorm/hubot-stackstorm#24]
Hello.

Not sure if this is hubot-stackstorm issue or not, but I am getting weirdly formatted output in the slack chatroom:
![Weird formatting](http://i.imgur.com/Zr5gBSs.png)

However running st2 run action [same action] from console it comes up just fine:
![console](http://i.imgur.com/kCICqmb.png)

Same nice output in WebUI of stackstorm2:
![webui](http://i.imgur.com/EGESReN.png)

And raw data from the st2 job itself looks fine too (at least I do not see backslashes there marking lines divisioning like in shell scripts when you do not want to have long lines you break them with backslashes):
![raw](http://i.imgur.com/FNkIkb8.png)

Could you guys look at it and point out at who's at fault here: stackstorm, hubot-slack or hubot-stackstorm? Thanks in advance.

**Comment by manasdk** [comment]
For some reason slack servers refuse to interpret '\n' as a LineFeed. Per slack documentation -

```
Multiline Messages

You can post multiline messages through Slack's APIs. Insert a newline by including the characters \n in your text. For example:

{
    "text": "This is a line of text.\nAnd this is another one."
}

The above JSON payload will be displayed in the channel as:

![image](https://cloud.githubusercontent.com/assets/1776099/8731154/56addfa0-2baa-11e5-8945-2804a93ad116.png)
```

see : https://api.slack.com/docs/formatting

**Comment by emptywee** [comment]
Apparently this is not true for formatted as 'pre' (triple-`) blocks, which is done by formatData call in the stackstorm.js. Also, where do backslashes come from? Look at my first screenshot.

**Comment by manasdk** [comment]
> where do backslashes come from?

Not sure.

**Comment by manasdk** [comment]
Those extra slashes look like are coming from https://github.com/StackStorm/st2contrib/blob/master/packs/hubot/actions/post_result.py#L16

**Comment by emptywee** [comment]
Not sure what made you think so, @manasdk Let's discuss it on the IRC channel :)

**Comment by manasdk** [comment]
Fixed. Closing issue.

**Comment by mmihir82** [comment]
Hello @manasdk I'm running into similar issue, I checked the `post_result.py` there isn't pyaml configured. Here is the output from slack message. 
<img width="499" alt="screen shot 2018-07-19 at 9 59 13 pm" src="https://user-images.githubusercontent.com/16388555/42985652-41bd3162-8ba7-11e8-803c-08f857075778.png">

When I run the `st2 run test.getint_workflow` I have created mine own, which calls ansible-playbook. 
output format looks good. 
<img width="710" alt="screen shot 2018-07-19 at 11 00 15 pm" src="https://user-images.githubusercontent.com/16388555/42985764-b108adf8-8ba7-11e8-953c-0950702e18e8.png">

Can you please help.

**Comment by LindsayHill** [comment]
Commenting on a closed issue often gets missed. Better to open a new issue.

That said, you may need to use something like https://github.com/StackStorm/st2_demos/blob/master/actions/workflows/link_flap_remed_workflow.yaml#L71

You should also think more about formatting your output nicely, rather than the default result display. Format it properly, using things like ``` around the fixed-width output. See https://github.com/StackStorm/st2_demos/blob/master/actions/workflows/link_flap_remed_workflow.yaml#L38
