### ISSUE TITLE
Tunable formatting prefix-suffix

### ISSUE THREAD

**Issue by emptywee** [StackStorm/hubot-stackstorm#26]
Hello.

Can we move hardcoded formatting markdown characters from format_data.js to some kind of configuration file? Not all chat servers support it. I had to temporary remove it for *Let's Chat* server.

```
[ansible@dc1udtlhkvm01 lib]$ fgrep -A1 '```' ./*
```
```js
./format_data.js://    return util.format('```\n%s```', table.toString());
./format_data.js-    return util.format('\n%s', table.toString());
--
./format_data.js://    return util.format('```\n%s\n```', JSON.stringify(data, null, 4));
./format_data.js-    return util.format('\n%s\n', JSON.stringify(data, null, 4));
--
./format_data.js://    return util.format('```\n%s\n```', data);
./format_data.js-    return util.format('\n%s\n', data);
```

Thanks :)

**Comment by jfryman** [comment]
@emptywee Do you have a PR with the change you made? We'll get this is queue, but if you have a working solution we can merge we'd be happy to look.

**Comment by emptywee** [comment]
@jfryman no, I don't have a PR for this. I just removed the markdown elements :) But if @manasdk or @lakshmi-kannan (or whoever else is developing hubot-stackstorm) could make it configurable, it would be really nice and more suitable to use across different chat servers.

**Comment by manasdk** [comment]
There is no formatting for most chat's. Only slack and hipchat get some special others don't really get any formatting support. Also, does look like you are referring to old code.

https://github.com/StackStorm/hubot-stackstorm/blob/master/lib/format_data.js#L95

**Comment by emptywee** [comment]
@manasdk gotcha. Will update :) I am retarded, as usual :D
