### ISSUE TITLE
hubot loads with a syntax error

### ISSUE THREAD

**Issue by cgallimore** [StackStorm/hubot-stackstorm#38]
This get emitted upon startup and repeats until Hubot eventually shuts down

```javascript
[Mon Sep 21 2015 17:34:11 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Mon Sep 21 2015 17:34:11 GMT+0000 (UTC)] ERROR SyntaxError: Unexpected token <
  at Object.parse (native)
  at /opt/hubot/node_modules/hubot-stackstorm/scripts/stackstorm.js:117:28
  at IncomingMessage.<anonymous> (/opt/hubot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

**Comment by emedvedev** [comment]
Should be working with the current version.

**Comment by runseb** [comment]
I just cloned this:
https://github.com/StackStorm/st2workroom

then:

    vagrant up st2

And I see the exact same error. I am trying the slack adapter. Could be a problem in the workroom.yaml file but I could not find a good example.

**Comment by dzimine** [comment]
Please try with the new packages - 
Ubuntu https://docs.stackstorm.com/latest/install/deb.html
RHEL/CentOS https://docs.stackstorm.com/latest/install/rhel7.html
Tested, works.

We are deprecating st2workroom.

**Comment by runseb** [comment]
So no Vagrant setup ?
I was following a June 2015 blog: https://stackstorm.com/2015/06/08/enhanced-chatops-from-stackstorm/?doing_wp_cron=1456936590.6317980289459228515625

**Comment by dzimine** [comment]
No, no more "heavy" vagrant setup: but still using vagrant is easy: spin one of the boxes from here https://docs.stackstorm.com/1.3/install/index.html, and either run AIO installer by `curl -sSL https://install.stackstorm.com/ | sudo sh -s -- -r v1.3.2` or go for new package installation, as pointed above. Given our direction to deprecate AIO, I recommend trying the new packages. 
There are correspondent script there too - https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-el7.sh https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.sh
They don't currently include Chatops step (PR coming) so today you'll run the script, and finish up Chatops with ["Setting up Chatops"](https://docs.stackstorm.com/latest/install/deb.html#setup-chatops)
or, for AIO installer,

**Comment by runseb** [comment]
thanks @dzimine the st2 install worked, but trying to get st2chatops package fails.

following:
https://docs.stackstorm.com/latest/install/deb.html#setup-chatops

`
$ st2 rule list --pack=chatops
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
ERROR: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - One of Token or API key required. for url: https://10.0.2.15/api/rules/?limit=50

vagrant@vagrant-ubuntu-trusty-64:~$ sudo apt-get install -y st2chatops
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package st2chatops
`
