### ISSUE TITLE
API call to /v1/actionalias fails over HTTPS

### ISSUE THREAD

**Issue by pixelrebel** [StackStorm/hubot-stackstorm#50]
Currently, hubot-stackstorm leverages the built-in http client (`node-scoped-http-client`) to make API calls.  This is separate from the authenticate method which uses the `request` library.  Currently the authentication works over https and returns an auth token.  However, the subsequent API calls fail over https with the error: `unable to verify the first certificate`.  Perhaps it's better to use the same approach for API calls as is used for authentication?  

Currently, the workaround for this is to put the following env into `hubot.conf` 
`export NODE_TLS_REJECT_UNAUTHORIZED=0`
but this approach is vulnerable to MITM attacks.

**Comment by manasdk** [comment]
@enykeev Can you take a look? Likely we can make this work with some of the work you are doing in https://github.com/StackStorm/hubot-stackstorm/pull/49

**Comment by enykeev** [comment]
This issue consists of two parts:
 - the good thing is that we're moving hubot-stackstorm to st2client.js which means that you would not need to use `NODE_TLS_REJECT_UNAUTHORIZED` in the next minor version of st2
 - the bad thing is that st2client.js basically doing the same thing under the hood and is also vulnerable to MITM

From what I can tell, there's no way to specifically say nodejs to only accept this particular self signed certificate and not the others. We already provide a locally generated root certificate on the last page of st2installer providing you're willing to add it to your system (I'm specifically emphasize that this certificate is generated on your server with, hopefully, cryptographically secure prng and no one has access to it except for those you're going to give it to).

Personally, I can't wait for Let’s Encrypt initiative to go GA so we can all forget about self-signed certs once and for all.

**Comment by pixelrebel** [comment]
Isn't hubot's client (`node-scoped-http-client`) based on `https.Agent`?  If so can we somehow add these options:
```
var options = {
  hostname: 'encrypted.google.com',
  port: 443,
  path: '/',
  method: 'GET',
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};
options.agent = new https.Agent(options);

var req = https.request(options, function(res) {
  ...
}
```
snippet from https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by jinpingh** [comment]
Have tested this issue on u16 with version `st2 3.1dev (8cffe7f), on Python 2.7.12` and could not duplicate issue.

Set `ST2_AUTH_URL` to use https , `ST2_AUTH_USERNAME`, and `ST2_AUTH_PASSWORD`, and unset `ST2_API_KEY`.  After `st2chatops` is up to running,  subsequent API calls are passed. From `st2chatops` log, there is no error message for `unable to verify the first certificate`. 

Tested setup `NODE_TLS_REJECT_UNAUTHORIZED`  value equals to `0` and `1` alone with above setting, both result are the same. 

Will close this issue for now. Please share information if you can duplicate it.
