### ISSUE TITLE
Hubot ignores ChatOps commands with parameters that include a dash in the key

### ISSUE THREAD

**Issue by chrisleavoy** [StackStorm/hubot-stackstorm#52]
See my note here: https://github.com/StackStorm/hubot-stackstorm/commit/e6a06f190ba5512231686fc9ccc94e592e3fde2f#diff-95dd92bf93762e48697a3823e2d7e7e2R51

**Comment by chrisleavoy** [comment]
@manasdk thoughts? Can we simply change \w+ to \S+ here?

**Comment by emedvedev** [comment]
@chrisleavoy thanks for reporting! I'm pretty sure it's safe to use `\S`; I'll test it some time during this week and get back to you.

**Comment by manasdk** [comment]
Yes \S+ should be safe. But again regexes so who knows :)

**Comment by chrisleavoy** [comment]
I just read the ActionChain doc, and it mentions: "Variable names can use letters, underscores, and numbers. No dashes! This applies to all variables: global vars, input parameters, DataStore keys, and published variables."

So maybe the issue here is that st2 doesn't error on parameters with a dash in them, like the gotcha implies it should, and the ansible pack needs to be rewritten to convert st2 parameters with an underscore to command line parameters with a dash?

I confused.

**Comment by manasdk** [comment]
Under the hood StackStorm uses jinja templating. Often the variables of all sort can end up being useful in a jinja template and in that a dash is really a minus sign causing all sorts of confusing errors. Therefore, we recommend not using `-` as a best practice. Given that it does suggest the ansible pack should perhaps be changed to use `_` instead of `-`.

**Comment by emedvedev** [comment]
I'm going to close the issue because using `-` is indeed incorrect, and it's the Ansible pack that should be reworked, but I'd like to point out that #53 makes the regexes more relaxed(although for a slightly different purpose) and will technically allow it.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1449838496012190
