### ISSUE TITLE
When using the action chatops.post_message Slack notifications display NO FALLBACK DEFINED

### ISSUE THREAD

**Issue by jon-middleton** [StackStorm/hubot-stackstorm#78]
While doing some testing of the ChatOPS interface, I've noticed notifications from StackStorm via hubot to Slack show the following text:

 > NO FALLBACK DEFINED

This is due to the fallback part of payload in `robot.emit 'slack-attachment', payload` has not been defined. This really should be a combination of the pretext and the text with no formatting. So that notifications (and systems that do not support attachments) can display the message.

Jon.

**Comment by jfryman** [comment]
@jon-middleton nice! Thanks for the heads up. We'll take a look at it. You don't happen to have a PR with you, do ya? :)

Thanks again!

**Comment by jon-middleton** [comment]
Afraid not, I just know how it works under the hood from my own modules in Hubot that send to Slack in the recent past.

**Comment by logic855** [comment]
I created a small pull request for this problem. @see https://github.com/StackStorm/hubot-stackstorm/pull/89

**Comment by emedvedev** [comment]
Fixed by #89.
