### ISSUE TITLE
Parameters are not passed when sending a direct message to hubot via slack

### ISSUE THREAD

**Issue by jmound** [StackStorm/hubot-stackstorm#92]
Using the [docs](https://docs.stackstorm.com/latest/aliases.html#basic) as an example, with this configuration:
```
formats:
  - "google {{query}}"
```
sending as a direct message to hubot via slack (untested on other messaging providers) `google foo` sets `query=foo`. However, sending: `! google foo` does not set `query=foo`

I tested this on 1.3.2. If someone else could verify, that would help.

**Comment by emedvedev** [comment]
@jmound: that's Hubot's expected behavior: when you use a channel message, you need to show it's meant for Hubot: either with `!`, bot's alias, or bot's username. When you send a DM, none of this is needed and you should just type `google foo`.

**Comment by jmound** [comment]
@emedvedev Needing the `!` in a channel and not needing it in a direct message is is clear.  

However, I'd think that the expected behavior of using `!` in a direct message would be either that it wouldn't trigger an action, or, if it does, query parameters would be passed. Instead, what sending it in a DM does is trigger the task, but without passing the parameters, just because the `!` is present.

The issue came up because I copied a channel message `! google foo`, and pasted it in to a direct message to the bot. As a direct message, the `foo` is ignored, yet `!google query=foo` in a direct message does pass the parameter.

**Comment by emedvedev** [comment]
Ok, I get it now :) Was able to reproduce the issue, will make sure to look into it next week. Thanks!

**Comment by emedvedev** [comment]
@jmound: I've just published `hubot-stackstorm` 0.3.6 which won't have this issue. It had to do with our command-matching regex searching for command in the string instead of matching it.

**Comment by jmound** [comment]
:+1:
